version: "3.9"

services:
  server:
    env_file:
      - .env
    container_name: 'ask-gigachat'
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:${APP_PORT}"
